This is makeindex, version 2.16 [TeX Live 2022] (kpathsea + Thai support).
Scanning style file ./Thesis.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file Thesis.acn....done (30 entries accepted, 0 rejected).
Sorting entries....done (144 comparisons).
Generating output file Thesis.acr....done (64 lines written, 0 warnings).
Output written in Thesis.acr.
Transcript written in Thesis.alg.
